#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 28 08:32:16 +03 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_state_machine_behav -key {Behavioral:sim_1:Functional:tb_state_machine} -tclbatch tb_state_machine.tcl -view /home/saturnine/lab_4/tb_state_machine_behav.wcfg -log simulate.log"
xsim tb_state_machine_behav -key {Behavioral:sim_1:Functional:tb_state_machine} -tclbatch tb_state_machine.tcl -view /home/saturnine/lab_4/tb_state_machine_behav.wcfg -log simulate.log

